filters:
  clientIdKey: clientId
  firstNameKey: firstName
  lastNameKey: lastName
  emailKey: email
  telephoneKey: telephone
  joinColumnOrderKey: client
  pageNumberKey: pageNumber
  pageSizeKey: pageSize
  ascSortingKey: asc
  descSortingKey: desc
  filtersKey: ${filters.firstNameKey},${filters.lastNameKey},${filters.emailKey},${filters.telephoneKey}